apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kafka-example
build:
  artifacts:
    - image: kafka-producer
      context: apps/kafka-producer
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'apps/kafka-producer/src/**/*.ts'
    - image: kafka-consumer
      context: apps/kafka-consumer
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'apps/kafka-consumer/src/**/*.ts'
deploy:
  kubectl:
    manifests:
      - infra/k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: kafka-producer
    port: 8081
    localPort: 8081
  - resourceType: service
    resourceName: kafka-consumer
    port: 8082
    localPort: 8082
