apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kafka-example
build:
  artifacts:
    - image: kafka-producer
      context: apps/kafka-producer
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'apps/kafka-producer/src/**/*.ts'
    - image: kafka-consumer-1
      context: apps/kafka-consumer-1
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'apps/kafka-consumer-1/src/**/*.ts'
deploy:
  kubeContext: jag
  kubectl:
    manifests:
      - apps/**/k8s/*.yaml
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: kafka-producer
    port: 8081
    localPort: 8081
  - resourceType: service
    resourceName: kafka-consumer-1
    port: 8082
    localPort: 8082
  # - resourceType: service
  #   resourceName: zookeeper
  #   port: 2181
  #   localPort: 2181
  # - resourceType: service
  #   resourceName: kafka
  #   port: 9092
  #   localPort: 9092
