apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  ports:
    - port: 8081
  type: NodePort
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: kafka-producer
          ports:
            - containerPort: 8081
