apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-1
spec:
  ports:
    - port: 8082
  type: NodePort
  selector:
    app: kafka-consumer-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-1
  template:
    metadata:
      labels:
        app: kafka-consumer-1
    spec:
      containers:
        - name: kafka-consumer-1
          image: kafka-consumer-1
          ports:
            - containerPort: 8082
